title: Jessie Curtner
keywords: "life coach, life coaching, corporate coaching, individual coaching, personal coach, personal coaching, executive coach, executive coaching"
baseurl: http://www.jessiecurtner.com
permalink: /blog/:title

owner: 
  name: Jessie Curtner  
  email: jcurtner@gmail.com
  phone: 415.385.0825
  skype: jessiecurtner
  address: 1348 San Bruno Ave.
  city: "San Francisco, CA 94110"

navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Private Coaching
    url: /private-coaching/
  - title: Business Coaching
    url: /business-coaching/
  - title: Contact
    url: /contact/
  - title: Blog
    url: /blog/