title: Jessie Curtner
keywords: "life coach, life coaching, corporate coaching, individual coaching, personal coach, personal coaching, executive coach, executive coaching"
baseurl: http://www.jessiecurtner.com
permalink: /blog/:title

owner:
  name: Jessie Curtner
  email: jcurtner@gmail.com
  phone: 415.385.0825
  skype: jessiecurtner

navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Coaching
    url: /coaching/
  - title: Contact
    url: /contact/
  - title: Blog
    url: /blog/
