title: Jessie Curtner
keywords: 
baseurl: http://www.jessiecurtner.com
permalink: /blog/:year/:month/:day/:title

owner: 
  name: Jessie Curtner  
  email: jcurtner@gmail.com
  phone: 415.385.0825
  skype: jessiecurtner
  address: 1348 San Bruno Ave.
  city: "San Francisco, CA 94110"

navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Individual Coaching
    url: /individual-coaching/
  - title: Corporate Coaching
    url: /corporate-coaching/
  - title: Contact
    url: /contact/